### ISSUE TITLE
마이페이지 기능 구현 및 사용자 기능 수정

### ISSUE THREAD

**Issue by mjttong** [somsomcartel/backend#11]
### Description

마이페이지 기능을 구현합니다.
사용자 인증 관련 예외 설정, 사용자 테이블 수정 작업 등을 진행합니다.

---
### ✅ To-do

- [x] 사용자 테이블 수정
- [x] 사용자 인가 예외 설정
- [x] 마이페이지 기능 구현

---
